### ISSUE TITLE
Attempting to use any addition modifier crashes library

### ISSUE THREAD

**Issue by jasedit** [syntruth/Dice-Bag#2]
Using the example provided in the README.md produces the following crash:
```
irb(main):001:0> require 'dicebag'
=> true
irb(main):002:0> dstr   = "(Damage) 2d8 + 5 + 1d6"
=> "(Damage) 2d8 + 5 + 1d6"
irb(main):003:0> dice   = DiceBag::Roll.new(dstr)
NoMethodError: undefined method `[]' for "5"@15:Parslet::Slice
	from /Library/Ruby/Gems/2.0.0/gems/dicebag-3.1.0/lib/dicebag/transform.rb:39:in `block in <class:Transform>'
	from /Library/Ruby/Gems/2.0.0/gems/parslet-1.7.1/lib/parslet/transform.rb:216:in `instance_eval'
	from /Library/Ruby/Gems/2.0.0/gems/parslet-1.7.1/lib/parslet/transform.rb:216:in `call_on_match'
	from /Library/Ruby/Gems/2.0.0/gems/parslet-1.7.1/lib/parslet/transform.rb:234:in `block in transform_elt'
	from /Library/Ruby/Gems/2.0.0/gems/parslet-1.7.1/lib/parslet/transform.rb:231:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/parslet-1.7.1/lib/parslet/transform.rb:231:in `transform_elt'
	from /Library/Ruby/Gems/2.0.0/gems/parslet-1.7.1/lib/parslet/transform.rb:184:in `apply'
	from /Library/Ruby/Gems/2.0.0/gems/parslet-1.7.1/lib/parslet/transform.rb:253:in `block in recurse_array'
	from /Library/Ruby/Gems/2.0.0/gems/parslet-1.7.1/lib/parslet/transform.rb:253:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/parslet-1.7.1/lib/parslet/transform.rb:253:in `recurse_array'
	from /Library/Ruby/Gems/2.0.0/gems/parslet-1.7.1/lib/parslet/transform.rb:189:in `apply'
	from /Library/Ruby/Gems/2.0.0/gems/dicebag-3.1.0/lib/dicebag.rb:160:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/dicebag-3.1.0/lib/dicebag/roll.rb:14:in `initialize'
	from (irb):3:in `new'
	from (irb):3
	from /usr/bin/irb:12:in `<main>'
```

**Comment by ekampp** [comment]
I'm getting the same error.

**Comment by syntruth** [comment]
Huh. I'll check this out when I get time. Sadly, for personal coding stuff, not a lot of that to go around lately...

**Comment by ekampp** [comment]
It seems to show up when you do `1d100 + 5` instead of `1d100 + 5d6`. It seems that adding a static modifier breaks it. 

I wanted to make a pull request, but there where no specs that I would run to prove my point before making code changes. :disappointed:

**Comment by syntruth** [comment]
Yeeeeah, one of those things I keep meaning to get around to. :( DiceBag is mostly a toy meant for my irc-bot, so never thought anyone would actually use it. Since it's now getting interest, I'll try to get it fixed up to be community friendly.

**Comment by ckib16** [comment]
I can get irb to `puts` a result out when changing the code like @ekampp said - use `"(Damage) 1d6 + 1d8"` instead of `"(Damage)1d6 + 8"`. In other words - don't use plain, static values like `+5`. Instead use all `#d#` values.

However, I still get the exact same error when trying to run the file via `ruby my_file_name.rb` intead of typing it line-by-line in pry or irb.

```
[23:10]~/coding/rails/fba $ ruby dice.rb 
/Users/Chris/.rvm/gems/ruby-2.2.3/gems/dicebag-3.1.0/lib/dicebag/transform.rb:39:in `block in <class:Transform>': undefined method `[]' for "5"@15:Parslet::Slice (NoMethodError)
	from /Users/Chris/.rvm/gems/ruby-2.2.3/gems/parslet-1.7.1/lib/parslet/transform.rb:216:in `instance_eval'
	from /Users/Chris/.rvm/gems/ruby-2.2.3/gems/parslet-1.7.1/lib/parslet/transform.rb:216:in `call_on_match'
	from /Users/Chris/.rvm/gems/ruby-2.2.3/gems/parslet-1.7.1/lib/parslet/transform.rb:234:in `block in transform_elt'
	from /Users/Chris/.rvm/gems/ruby-2.2.3/gems/parslet-1.7.1/lib/parslet/transform.rb:231:in `each'
	from /Users/Chris/.rvm/gems/ruby-2.2.3/gems/parslet-1.7.1/lib/parslet/transform.rb:231:in `transform_elt'
	from /Users/Chris/.rvm/gems/ruby-2.2.3/gems/parslet-1.7.1/lib/parslet/transform.rb:184:in `apply'
	from /Users/Chris/.rvm/gems/ruby-2.2.3/gems/parslet-1.7.1/lib/parslet/transform.rb:253:in `block in recurse_array'
	from /Users/Chris/.rvm/gems/ruby-2.2.3/gems/parslet-1.7.1/lib/parslet/transform.rb:253:in `map'
	from /Users/Chris/.rvm/gems/ruby-2.2.3/gems/parslet-1.7.1/lib/parslet/transform.rb:253:in `recurse_array'
	from /Users/Chris/.rvm/gems/ruby-2.2.3/gems/parslet-1.7.1/lib/parslet/transform.rb:189:in `apply'
	from /Users/Chris/.rvm/gems/ruby-2.2.3/gems/dicebag-3.1.0/lib/dicebag.rb:160:in `parse'
	from /Users/Chris/.rvm/gems/ruby-2.2.3/gems/dicebag-3.1.0/lib/dicebag/roll.rb:14:in `initialize'
	from dice.rb:4:in `new'
	from dice.rb:4:in `<main>'
```

**Comment by ekampp** [comment]
I went and made my own lib, super fast and dirty: https://github.com/DarkHeresyOnline/dice

If any of it is of interest I would be happy to backport in another PR.

**Comment by syntruth** [comment]
Okay.  I have found the issue here after writing some specs for this lib finally. I'll be pushing an update here soon.

The issue was in the Parslet::Transform sub-class, where it was not matching simple op=>values, and when it did match the xdx sub-trees, a bug was wiping out the op-string.

Kinda, sorta, super really embarrassing, really. :)

**Comment by syntruth** [comment]
And 3.2.0 pushed. Let me know if you still have any issues.  If not, I'll close this issue soon.

**Comment by syntruth** [comment]
Added a few more updates. Sorry for the bugs earlier! They were quite stupid, honestly, but now I think the lib is in a much better position for working on it when I get more time. I've noted a few things I wanna do in the parser and transform classes to streamline things a bit more. Gonna close this issue now.
