### ISSUE TITLE
Add support for Fudge/Fate dice

### ISSUE THREAD

**Issue by fabiocosta0305** [syntruth/Dice-Bag#6]
Please, add support for Fudge/Fate dice via the dF notation, like in 4dF

**Comment by syntruth** [comment]
Sorry for the long delay! I am actually looking into this as well as a few other features, as I hope to have time to work on this lib again. :)

**Comment by syntruth** [comment]
While there is no parsing for dF format, there is now an official Fudge/FATE system included. See the README at the bottom.
